  version: '3.9'

  services:
    database_ignite:
      image: postgres
      container_name: database_ignite
      restart: always
      ports: 
        - 5432:5432
      environment: 
        POSTGRES_PASSWORD: docker
        POSTGRES_USER: docker
        POSTGRES_DB: ignite
      volumes:
        - pgdata:/data/postgres

    # app:
    #   build: .
    #   container_name: rentex
    #   ports: 
    #     - 3333:3333
    #   volumes: 
    #     - .:/usr/app
    #   links: 
    #     - database_ignite
    #   depends_on: 
    #     - database_ignite

  volumes:
    pgdata: 
      driver: local      
    