name: Rentx-API

on:
  push: 
    branches: 
      - main
jobs:
  run_develop: 
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
    - name: install depencies
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - run: npm ci
    
    - name: build
    - run: npm build
    
    - uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{secrets.SSH_HOST }}
        port: ${{ secrets.PORT }}
        source: "., !node_modules"
        target: "test"
